### ISSUE TITLE
config-changed hook fails when using local 'bundled' deb

### ISSUE THREAD

**Issue by ryan-beisner** [jenkinsci/jenkins-charm#1]
For offline or restricted-network installations which cannot reach the upstream deb repos, the jenkins.deb can be placed in ./files/ dir for deployment.

However, when the config-changed hook fires, it tries to do an apt install of jenkins anyway.  That prevents this offline install feature from working (as it did in the previous bash version of the charm).

https://github.com/jenkinsci/jenkins-charm/blob/d526f135d113a9b36a13dca12a71290f77f3d397/hooks/jenkins_hooks.py#L73

**Comment by lutostag** [comment]
Should work now. If it is still effecting you, feel free to reopen.
