### ISSUE TITLE
References to free's repo

### ISSUE THREAD

**Issue by lutostag** [jenkinsci/jenkins-charm#10]
There are several references to free's repo. (in the metadata.yaml and the travis badge in the readme for example).

BTW I updated interfaces.juju.solutions to point to free's interfaces for the moment, we might want to find a better place to host them if they require changes in the future (~cicd group added for perms there).

**Comment by freeekanayaka** [comment]
@lutostag do you intend to work on fixing the references in the core jenkins layer branch or should I take initiative? I guess we also need to ask whoever is in charge enable Travis jobs for the jenkinsci branch.

Re the interfaces I'm not sure either where they should go. The best would be under gh/jenkinsci itself.

**Comment by lutostag** [comment]
Looks like marco got the travis going. And fixed the references before. So closing this...

But yeah dunno if we can more repos for the interfaces under the project, but I think they are fine where they are for now. (btw filed https://github.com/bcsaller/juju-interface/issues/9 to see if we could use separate branches in tree in the future, which would make sense to me).
