### ISSUE TITLE
Charm should allow configuring Jenkins to use a proxy

### ISSUE THREAD

**Issue by barryprice** [jenkinsci/jenkins-charm#125]
### What feature do you want to see added?

The charm should allow the operator to configure Jenkins (and only Jenkins) to use a proxy server.

There is an existing pull request to apply any model-specific proxy configuration here:
https://github.com/jenkinsci/jenkins-charm/pull/53

As well as another PR to apply any system-wide proxy environment settings here:
https://github.com/jenkinsci/jenkins-charm/pull/41

However in this use case, we may want Jenkins specifically to use a proxy, without also forcing other programs to do so (e.g. apt-get, subordinates etc).

I have a WIP branch here that may be useful - it borrows heavily from the second PR linked above, but my configuration unit test is failing for reasons that aren't quite obvious to me at this time:

https://github.com/jenkinsci/jenkins-charm/compare/master...barryprice:jenkins-charm:master

**Comment by mthaddon** [comment]
This was implemented in https://github.com/jenkinsci/jenkins-charm/pull/128
