### ISSUE TITLE
The charm allows proxy configuration but lacks the `no_proxy` variable

### ISSUE THREAD

**Issue by canonical-is** [jenkinsci/jenkins-charm#148]
### Jenkins and plugins versions report

The charm allows proxy configuration through the variables `proxy-hostname`, `proxy-password`, `proxy-port`, and `proxy-username` but it doesn't have a `no-proxy`.

This missing configuration makes working with a proxy cumbersome as not everything in Jenkins should go through the proxy and there's no way to do that in the charm.

I consider this a bug because the configuration is incomplete.

### What Operating System are you using (both controller, and any agents involved in the problem)?

Charm revision 41 

### Reproduction steps

`juju config jenkins | grep proxy`

### Expected Results

Being able to set `no_proxy` through juju config.

### Actual Results

The only place to set no-proxy is in the Jenkins UI.

**Comment by mthaddon** [comment]
This looks to be `configure_proxy` in `lib/charms/layer/jenkins/api.py` (after exposing a way for the operator to set this as appropriate).

**Comment by yanksyoon** [comment]
Released to stable :)
