### ISSUE TITLE
charm install fails on Xenial (need to pre-install python 2)

### ISSUE THREAD

**Issue by ryan-beisner** [jenkinsci/jenkins-charm#2]
The charm install fails on 16.04 Xenial, which by default includes python 3, but not python 2.   Python 2 is installable, and the install hook should do a pre-install of Python 2 to address this.

**Comment by ryan-beisner** [comment]
OpenStack charms had the same issue, see install and install.real in https://github.com/openstack/charm-keystone/tree/master/hooks as an example.

**Comment by lutostag** [comment]
Fixed with latest version. Deploys fine on xenial.
