### ISSUE TITLE
[Question]: any plan to publish the new revision to the charms store ? thanks

### ISSUE THREAD

**Issue by eviweb** [jenkinsci/jenkins-charm#22]

**Comment by freeekanayaka** [comment]
I'd like too, but have not enough privileges to do so.

I've pinged @marcoceppi multiple times, but no reply so far.

**Comment by marcoceppi** [comment]
There was a push of the charm a few weeks ago, I can manually do one again but I think it's better to give @freeekanayaka write access as well (have done so).

I'm also going to add an edge channel travis CI job so we will only need to release instead of push new revisions up.

**Comment by freeekanayaka** [comment]
Pushed to stable.

**Comment by eviweb** [comment]
Many thanks guys
