### ISSUE TITLE
[WishList]: Support of Haproxy reverse proxy relation

### ISSUE THREAD

**Issue by eviweb** [jenkinsci/jenkins-charm#25]
Hi,
is it possible to add the support of the haproxy reverseproxy:http relation to be able to run jenkins behind this reverse proxy ?
Thanks

**Comment by freeekanayaka** [comment]
Yes, it's already implemented. Give a look a the integration tests:

https://github.com/jenkinsci/jenkins-charm/blob/master/tests/website.py#L17

you can simply relate haproxy and jenkins.

Perhaps the documentation should mention this.

**Comment by eviweb** [comment]
@freeekanayaka,
sorry I didn't check the new revision,
thanks
Eric
