### ISSUE TITLE
need a jenkins-slave charm for Trusty, Xenial and onward

### ISSUE THREAD

**Issue by ryan-beisner** [jenkinsci/jenkins-charm#3]
There is a Precise-series jenkins-slave charm, and potentially some forks out there to enable later series and features.  Re-consolidate ftw.

**Comment by jamesbeedy** [comment]
@ryan-beisner can we get a priority tag for this?

**Comment by ryan-beisner** [comment]
@jamesbeedy  Agree, this is a real need.  Let's see if we can make this happen.

**Comment by kvalev** [comment]
Are there any plans to add Xenial support for the official jenkins-slave charm? None of the slave charms seem to work with the newest master version.

**Comment by hloeung** [comment]
I'm working on a jenkins-slave charm here - https://launchpad.net/jenkins-slave-charm

**Comment by mthaddon** [comment]
This has now been published https://jujucharms.com/u/jenkins-ci-charmers/jenkins-slave - I'll leave this issue open until it's been promulgated, which I'd expect to happen sometime next week after some discussions.

**Comment by mthaddon** [comment]
This has now been promulgated. https://jujucharms.com/jenkins-slave
