### ISSUE TITLE
Jenkins deb upgraded and juju charm fails to deploy

### ISSUE THREAD

**Issue by ikepanhc** [jenkinsci/jenkins-charm#46]
At Sep 12th we have jenkins deb upgrade[1] from 2.121.3 to 2.138.1. After that `juju deploy jenkins` fails with authentication fails. 
Workaround is to use "release: https://pkg.jenkins.io/debian-stable/binary/jenkins_2.121.3_all.deb" so that old debs are used.

[1] http://pkg.jenkins-ci.org/debian-stable/
[2] jenkins.JenkinsException: Error in request. Possibly authentication failed [401]: Invalid password/token for user: admin

**Comment by jamesbeedy** [comment]
this is https://github.com/jenkinsci/jenkins-charm/issues/47

**Comment by mthaddon** [comment]
#47 is now fixed, marking this as resolved.
