### ISSUE TITLE
layer:jenkins tries to install and configure up jenkins

### ISSUE THREAD

**Issue by hloeung** [jenkinsci/jenkins-charm#54]
Hi,

I'm trying to rewrite the jenkins-slave charm using the reactive framework.

When trying to use just the jenkins-slave interface, it fails as it needs charms.layer.jenkins for 'credentials' and 'api', see https://github.com/freeekanayaka/interface-jenkins-slave/blob/master/requires.py#L16.

When trying to use the jenkins layer, it tries to install and configure up Jenkins.

Any chance we could have the layer split out so it could be reused elsewhere?

**Comment by hloeung** [comment]
https://github.com/freeekanayaka/interface-jenkins-slave/issues/1

**Comment by mthaddon** [comment]
@hloeung I believe this can be closed out now? Will do so pre-emptively, but let me know if it needs re-opening.
