### ISSUE TITLE
promulgate to charmstore

### ISSUE THREAD

**Issue by jamesbeedy** [jenkinsci/jenkins-charm#9]
Need this promulgated to charm store!

**Comment by freeekanayaka** [comment]
@marcoceppi do I have the rights to do so yet? If not, mind actually making this last mile? It's been a while now..

**Comment by marcoceppi** [comment]
Done: https://jujucharms.com/jenkins/ Sorry for the delay! I'll work on a travisci file that pushes merges to edge and we can just cherry pick/release as sees fit

**Comment by freeekanayaka** [comment]
@marcoceppi nice, re the automatic pushes to edge.
