### ISSUE TITLE
Update plugin should not try to safeRestart when nothing have been updated

### ISSUE THREAD

**Issue by darkalia** [jenkinsci/jenkins-charm#94]
The current workflow is:
* check jenkins.plugins.last_update
* if the last update is > at plugins-auto-update-interval, update the plugins
* after updating the plugins, do a safeRestart

This behavior might be suited for short builds, but as soon as long builds occurs, it doesn't work:
* plugin get's updated
* safeRestart is initiated
* builds are blocked until the last build is done, other builds are put in the queue, waiting the restart
* the long build is alone, blocking all other builds until he's finished
* rinse and repeat

I suggest we
1. Do not issue any restart when nothing has changed
2. Update plugins way less often than we do
3. Create a juju action to force this, cancelling all on going builds when a CVE needs to be quickly fixed.

**Comment by alejdg** [comment]
Addressing 1.:
This is already supposed to work like that. This is the place where the validation happens: https://github.com/jenkinsci/jenkins-charm/blob/master/lib/charms/layer/jenkins/plugins.py#L154

I think there's another issue going on where a new plugin version is downloaded but for some reason is ignored by jenkins. The next time the update runs, jenkins indicates the plugin is still outdated so the charm follows the same process again and restarts again.

The other two suggestions seem totally reasonable to me.

**Comment by darkalia** [comment]
> Addressing 1.:
> This is already supposed to work like that. This is the place where the validation happens: https://github.com/jenkinsci/jenkins-charm/blob/master/lib/charms/layer/jenkins/plugins.py#L154
> 
Ah I see, the code path I modified would be useful only if we change the plugins config and it result in a no-op. Which could still be useful.
I think those part should be shared between the 2 processes to be honest, this way if someone "hack" the list of plugins by installing a new one, the next update-status would remove it if "remove-unlisted-plugin" is set.

> I think there's another issue going on where a new plugin version is downloaded but for some reason is ignored by jenkins. The next time the update runs, jenkins indicates the plugin is still outdated so the charm follows the same process again and restarts again.
> 

I'll check again and modify the code accordingly then.

> The other two suggestions seem totally reasonable to me.
Probably in another PR though.

**Comment by darkalia** [comment]
Closing this issue as the main assumption to open it is proven wrong.
Will create other issues for the subsequent work that needs to be done.

**Comment by paride** [comment]
@darkalia can you please @mention me in the new issues? I'd like to follow progress and the notification will help me find out what to follow. Thanks!
